# Relative paths work OK as long as you start the tool from its local dir
template_path: tool

# This folder gets copied into the output directory
template_static_path: assets

# Templates should have filenames starting in template-
default_template: template-doc.html
default_pdf_template: template-forpdf.html

# HTML, PDF, GFM all get output here
out_path: out

# MD files should be here (and in subdirs)
content_path: content

# This folder gets copied into the output directory
content_static_path: img

# PDF creation needs a dir for temporary files
temporary_files_path: /tmp/

default_filters:
    - multicode_tabs
    - standardize_header_ids
    - buttonize
    - callouts
    - badges
    - link_replacement

callout_class: "devportal-callout"

cover_page:
    name: Overview
    html: index.html
    sidebar: "off"
    template: template-index.html

targets:
    # First member is the default that gets built when target not specified
    -   name: local
        display_name: Ripple Developer Portal

    -   name: ripple.com
        display_name: Ripple Developer Center
        template: template-contentwithtoc.html
        link_subs:
            "reference-rippled.html": https://ripple.com/build/rippled-apis/
            "reference-rippleapi.html": https://ripple.com/build/rippleapi/
            "reference-transaction-format.html": https://ripple.com/build/transactions/
            "reference-ledger-format.html": https://ripple.com/build/ledger-format/
            "reference-data-api.html": https://ripple.com/build/data-api-v2/
            "reference-amendments.html": https://ripple.com/build/known-amendments/
            "tutorial-multisign.html": https://ripple.com/build/how-to-multi-sign/
            "concept-issuing-and-operational-addresses.html": https://ripple.com/build/issuing-operational-addresses/
            "tutorial-reliable-transaction-submission.html": https://ripple.com/build/reliable-transaction-submission/
            "tutorial-rippleapi-beginners-guide.html": https://ripple.com/build/rippleapi-beginners-guide/
            "tutorial-rippled-setup.html": https://ripple.com/build/rippled-setup/
            "tutorial-gateway-guide.html": https://ripple.com/build/gateway-guide/
            "tutorial-paychan.html": https://ripple.com/build/payment-channels-tutorial/
            "tutorial-escrow.html": https://ripple.com/build/escrow-tutorials/
            "tutorial-listing-xrp.html": https://ripple.com/build/listing-xrp-exchange/
            # Jha added placeholder link_sub below - need to get the permalink from Wordpress
            "tutorial-build-run-rippled-ubuntu.html": https://ripple.com/build/build-run-rippled-ubuntu/
            "concept-accounts.html": https://ripple.com/build/accounts/
            "concept-amendments.html": https://ripple.com/build/amendments/
            "concept-consensus.html": https://ripple.com/build/xrp-ledger-consensus-process/
            "concept-escrow.html": https://ripple.com/build/escrow/
            "concept-reaching-consensus.html": https://ripple.com/build/reaching-consensus-xrp-ledger/
            "concept-fee-voting.html": https://ripple.com/build/fee-voting/
            "concept-fees.html": https://ripple.com/build/fees-disambiguation/
            "concept-freeze.html": https://ripple.com/build/freeze/
            "concept-paths.html": https://ripple.com/build/paths/
            "concept-partial-payments.html": https://ripple.com/build/partial-payments/
            "concept-reserves.html": https://ripple.com/build/reserves/
            "concept-stand-alone-mode.html": https://ripple.com/build/stand-alone-mode/
            "concept-transaction-cost.html": https://ripple.com/build/transaction-cost/
            "concept-transfer-fees.html": https://ripple.com/build/transfer-fees/
            "concept-noripple.html": https://ripple.com/build/understanding-the-noripple-flag/
            "gb-2015-06.html": https://ripple.com/build/gateway-guide/gb-2015-06-corrections-autobridging/
            "gb-2015-05.html": https://ripple.com/build/gateway-guide/gb-2015-05-historical-ledger-query-migration/
            "ripple-api-tool.html": https://ripple.com/build/websocket-tool/
            "data-api-v2-tool.html": https://ripple.com/build/data-api-tool/
            "concept-money.html": https://ripple.com/build/money-xrp-ledger/
            "reference-currency.html": https://ripple.com/build/currency-format/
            "concept-demurrage.html": https://ripple.com/build/demurrage/
            "concept-depositauth.html": https://ripple.com/build/deposit-authorization/
        image_subs:
            "img/funds_flow_diagram.png": https://cdn.ripple.com/wp-content/uploads/2016/03/funds_flow_diagram.png
            "img/e2g-01.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/e2g-01.png
            "img/e2g-02.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/e2g-02.png
            "img/e2g-03.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/e2g-03.png
            "img/e2g-with_transferrate.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/e2g-with_transferrate.png
            "img/transfer_fees_example.png": https://cdn.ripple.com/wp-content/uploads/2015/06/transfer_fees_example1.png
            "img/ledger-process.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/ledger-process.png
            "img/ledger-components.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/ledger-components.png
            "img/ledger-indexes.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/ledger-indexes.png
            "img/ledger-history.png": https://cdn.ripple.com/wp-content/uploads/2014/12/Overview-of-Ripple-Ledger-Consensus-and-Validation-12_12-02.png
            "img/ledger-changes.png": https://cdn.ripple.com/wp-content/uploads/2014/12/Overview-of-Ripple-Ledger-Consensus-and-Validation-12_12-03.png
            "img/paths-examples.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/paths-examples.png
            "img/paths-default_paths.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/paths-default_paths.png
            "img/noripple-01.png": https://cdn.ripple.com/wp-content/uploads/2015/04/noripple-01.png
            "img/noripple-02.png": https://cdn.ripple.com/wp-content/uploads/2015/04/noripple-02.png
            "img/noripple-03.png": https://cdn.ripple.com/wp-content/uploads/2015/01/noripple-03.png
            "img/noripple-04.png": https://cdn.ripple.com/wp-content/uploads/2015/01/noripple-04.png
            "img/noripple-05.png": https://cdn.ripple.com/wp-content/uploads/2015/01/noripple-05.png
            "img/noripple-06.png": https://cdn.ripple.com/wp-content/uploads/2015/01/noripple-06.png
            "img/key-address-rels.png": https://cdn.ripple.com/wp-content/uploads/2017/05/key-address-rels.png
            "img/paychan-flow.png": https://cdn.ripple.com/wp-content/uploads/2017/05/paychan-flow1.png
            "img/consensus-agreed-transaction-set.png": https://cdn.ripple.com/wp-content/uploads/2014/12/Overview-of-Ripple-Ledger-Consensus-and-Validation-12_12-06.png
            "img/consensus-calculate-validation.png": https://cdn.ripple.com/wp-content/uploads/2014/12/Overview-of-Ripple-Ledger-Consensus-and-Validation-12_12-07.png
            "img/consensus-candidate-transaction-sets.png": https://cdn.ripple.com/wp-content/uploads/2014/12/Overview-of-Ripple-Ledger-Consensus-and-Validation-12_12-05.png
            "img/consensus-declare-validation.png": https://cdn.ripple.com/wp-content/uploads/2014/12/Overview-of-Ripple-Ledger-Consensus-and-Validation-12_12-08.png
            "img/consensus-validated-ledger.png": https://cdn.ripple.com/wp-content/uploads/2014/12/Overview-of-Ripple-Ledger-Consensus-and-Validation-12_12-09.png
            "img/xrp-ledger-network.png": https://cdn.ripple.com/wp-content/uploads/2014/12/Overview-of-Ripple-Ledger-Consensus-and-Validation-12_12-04.png
            "img/escrow-success-flow.png": https://cdn.ripple.com/wp-content/uploads/2017/09/escrow-success-flow.png
            "img/escrow-cancel-flow.png": https://cdn.ripple.com/wp-content/uploads/2017/09/escrow-cancel-flow.png
            "img/currency-code-format.png": https://cdn.ripple.com/wp-content/uploads/2017/11/currency-code-format.png
            "img/currency-number-format.png": https://cdn.ripple.com/wp-content/uploads/2017/11/currency-number-format.png
            "img/demurrage-currency-code-format.png": https://cdn.ripple.com/wp-content/uploads/2017/11/demurrage-currency-code-format.png

    -   name: rippled-setup
        display_name: rippled Setup Guide
        link_subs:
            "reference-rippled.html": https://ripple.com/build/rippled-apis/

pages:
# References are exhaustive lists of commands and options
    -   name: RippleAPI
        category: References
        html: reference-rippleapi.html
        # Currently this is the only page that's fetched remotely.
        md: https://raw.githubusercontent.com/ripple/ripple-lib/e6d71471e26ca253e762fc7034859951b5d31c47/docs/index.md
        filters:
            - remove_doctoc
            - add_version
        targets:
            - local
            - ripple.com

    -   name: rippled
        category: References
        html: reference-rippled.html
        md: reference-rippled.md
        targets:
            - local
            - ripple.com

    -   name: Transaction Format
        category: References
        html: reference-transaction-format.html
        md: reference-transaction-format.md
        targets:
            - local
            - ripple.com

    -   name: Ledger Format
        category: References
        html: reference-ledger-format.html
        md: reference-ledger-format.md
        targets:
            - local
            - ripple.com

    -   name: Ripple Data API v2
        category: References
        html: reference-data-api.html
        md: reference-data-api.md
        targets:
            - local
            - ripple.com

    -   md: reference-currency.md
        category: References
        html: reference-currency.html
        targets:
            - local
            - ripple.com

    -   md: reference-amendments.md
        category: References
        html: reference-amendments.html
        targets:
            - local
            - ripple.com

# Tutorials are step-by-step guides to a specific goal
    -   name: How to Multi-Sign
        category: Tutorials
        html: tutorial-multisign.html
        md: tutorial-multisign.md
        targets:
            - local
            - ripple.com

    -   category: Tutorials
        html: tutorial-paychan.html
        md: tutorial-paychan.md
        targets:
            - local
            - ripple.com

        # This is more like a "best practices" doc than Tutorials...
    -   name: Issuing and Operational Addresses
        category: Tutorials
        html: concept-issuing-and-operational-addresses.html
        md: concept-issuing-and-operational-addresses.md
        targets:
            - local
            - ripple.com

    -   name: Reliable Transaction Submission
        category: Tutorials
        html: tutorial-reliable-transaction-submission.html
        md: tutorial-reliable-transaction-submission.md
        targets:
            - local
            - ripple.com

    -   name: RippleAPI Beginners Guide
        category: Tutorials
        html: tutorial-rippleapi-beginners-guide.html
        md: tutorial-rippleapi-beginners-guide.md
        targets:
            - local
            - ripple.com

    -   name: rippled Setup
        category: Tutorials
        html: tutorial-rippled-setup.html
        md: tutorial-rippled-setup.md
        targets:
            - local
            - ripple.com
            - rippled-setup

        # The Gateway Guide is also a poor fit for the "tutorials" category
    -   name: Gateway Guide
        category: Tutorials
        html: tutorial-gateway-guide.html
        md: tutorial-gateway-guide.md
        targets:
            - local
            - ripple.com

# Listing XRP as an Exchange
    -   category: Tutorials
        html: tutorial-listing-xrp.html
        md: tutorial-listing-xrp.md
        targets:
            - local
            - ripple.com

    -   md: tutorial-escrow.md
        html: tutorial-escrow.html
        category: Tutorials
        targets:
            - local
            - ripple.com

# Jha added entry below - not sure if this is the proper sequence.
    -   name: Build and Run rippled on Ubuntu
        md: tutorial-build-run-rippled-ubuntu.md
        html: tutorial-build-run-rippled-ubuntu.html
        category: Tutorials
        targets:
            - local
            - ripple.com

#Features describe how the XRP Ledger works in a mostly conceptual manner
    -   name: Accounts
        category: Features
        html: concept-accounts.html
        md: concept-accounts.md
        targets:
            - local
            - ripple.com

    -   name: Amendments
        category: Features
        html: concept-amendments.html
        md: concept-amendments.md
        targets:
            - local
            - ripple.com

    -   name: Consensus Process
        category: Features
        html: concept-consensus.html
        md: concept-consensus.md
        targets:
            - local
            - ripple.com

    -   name: Reaching Consensus in the XRP Ledger
        category: Features
        html: concept-reaching-consensus.html
        md: concept-reaching-consensus.md
        targets:
            - local
            - ripple.com

    -   md: concept-depositauth.md
        category: Features
        targets:
            - local
            - ripple.com

    -   md: concept-escrow.md
        category: Features
        targets:
            - local
            - ripple.com

    -   name: Fee Voting
        category: Features
        html: concept-fee-voting.html
        md: concept-fee-voting.md
        targets:
            - local
            - ripple.com

    -   name: Fees (Disambiguation)
        category: Features
        html: concept-fees.html
        md: concept-fees.md
        targets:
            - local
            - ripple.com

    -   name: Freeze
        category: Features
        html: concept-freeze.html
        md: concept-freeze.md
        targets:
            - local
            - ripple.com

    -   md: concept-money.md
        category: Features
        html: concept-money.html
        targets:
            - local
            - ripple.com

    -   md: concept-demurrage.md
        category: Features
        html: concept-demurrage.html
        targets:
            - local
            - ripple.com

    -   md: concept-partial-payments.md
        category: Features
        html: concept-partial-payments.html
        targets:
            - local
            - ripple.com

    -   name: Paths
        category: Features
        html: concept-paths.html
        md: concept-paths.md
        targets:
            - local
            - ripple.com

    -   name: Reserves
        category: Features
        html: concept-reserves.html
        md: concept-reserves.md
        targets:
            - local
            - ripple.com

    -   name: Stand-Alone Mode
        category: Features
        html: concept-stand-alone-mode.html
        md: concept-stand-alone-mode.md
        targets:
            - local
            - ripple.com

    -   name: Transaction Cost
        category: Features
        html: concept-transaction-cost.html
        md: concept-transaction-cost.md
        targets:
            - local
            - ripple.com

    -   name: Transfer Fees
        category: Features
        html: concept-transfer-fees.html
        md: concept-transfer-fees.md
        targets:
            - local
            - ripple.com

    -   name: Understanding the NoRipple flag
        category: Features
        html: concept-noripple.html
        md: concept-noripple.md
        targets:
            - local
            - ripple.com

    -   name: "GB-2015-06: Corrections to Autobridging"
        category: Gateway Bulletins
        html: gb-2015-06.html
        md: gb-2015-06.md
        targets:
            - local
            - ripple.com

    -   name: "GB-2015-05: Historical Ledger Query Migration"
        category: Gateway Bulletins
        html: gb-2015-05.html
        md: gb-2015-05.md
        targets:
            - local
            - ripple.com

# API tools are interactive software for interfacing with real APIs
    -   name: WebSocket API Tool
        category: API Tools
        html: ripple-api-tool.html
        sidebar: custom
        targets:
            - local
            - ripple.com
        template: template-ripple-api-tool.html

    -   name: Data API v2 Tool
        category: API Tools
        html: data-api-v2-tool.html
        methods_js: js/apitool-methods-data_v2.js
        rest_host: https://data.ripple.com
        doc_page: reference-data-api.html
        sidebar: custom
        targets:
            - local
            - ripple.com
        template: template-rest-api-tool.html

    -   name: rippled JSON-RPC Tool
        # This tool requires a local server w/ reverse proxy
        category: API Tools
        html: tool-jsonrpc.html
        methods_js: js/apitool-methods-jsonrpc.js
        rest_host: http://localhost/rippled
        doc_page: reference-rippled.html
        sidebar: custom
        targets:
            - local
            - ripple.com
        template: template-rest-api-tool.html

    -   name: Page Manifest
        # Used to inform the ripple.com code what pages it should map
        html: devportal-manifest.php
        template: template-manifest.php
        targets:
            - ripple.com

# Link Checker Config ------------------------------------------------------- #

ignore_anchors_in:
    - data-api-v2-tool.html
    - ripple-api-tool.html
    - tool-jsonrpc.html

#Sometimes, a link is not really problematic, but the link checker detects it
# as such and the easiest solution is to ignore it.
known_broken_links:
    # Strangely, Python doesn't like the cert here. Firefox is OK with it.
    - https://validators.ripple.com

    # These PDFs download OK in a browser
    - http://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX%3A32015R0847
    - http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2006:345:0001:0009:EN:PDF

# Style Checker Config ------------------------------------------------------ #

word_substitutions_file: tool/word_substitutions.yaml
phrase_substitutions_file: tool/phrase_substitutions.yaml
