# Relative paths work OK as long as you start the tool from its local dir
template_path: .

# This folder gets copied into the output directory
template_static_path: ../assets

# Templates should have filenames starting in template-
default_template: template-doc.html
pdf_template: template-forpdf.html

# HTML, PDF, GFM all get output here
out_path: ..

# MD files should be here (and in subdirs)
content_path: ../content

# This folder gets copied into the output directory
content_static_path: ../img

# PDF creation needs a dir for temporary files
temporary_files_path: /tmp/

prince_executable: prince

default_filters:
    - multicode_tabs
    - standardize_header_ids
    - buttonize
    - callouts
    - badges

targets:
    # First member is the default that gets built when target not specified
    -   name: local
        display_name: Ripple Developer Portal

    -   name: ripple.com
        display_name: Ripple Developer Center
        template: template-contentwithtoc.html
        image_subs:
            "img/funds_flow_diagram.png": https://ripple.com/wp-content/uploads/2016/03/funds_flow_diagram.png
            "img/e2g-01.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/e2g-01.png
            "img/e2g-02.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/e2g-02.png
            "img/e2g-03.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/e2g-03.png
            "img/e2g-with_transferrate.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/e2g-with_transferrate.png
            "img/transfer_fees_example.png": https://ripple.com/wp-content/uploads/2015/06/transfer_fees_example1.png
            "img/ledger-process.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/ledger-process.png
            "img/ledger-components.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/ledger-components.png
            "img/ledger-indexes.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/ledger-indexes.png
            "img/paths-examples.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/paths-examples.png
            "img/paths-default_paths.png": https://ripple.com/wp-content/themes/ripple-beta/assets/img/paths-default_paths.png
            "img/noripple-01.png": https://ripple.com/wp-content/uploads/2015/04/noripple-01.png
            "img/noripple-02.png": https://ripple.com/wp-content/uploads/2015/04/noripple-02.png
            "img/noripple-03.png": https://ripple.com/wp-content/uploads/2015/01/noripple-03.png
            "img/noripple-04.png": https://ripple.com/wp-content/uploads/2015/01/noripple-04.png
            "img/noripple-05.png": https://ripple.com/wp-content/uploads/2015/01/noripple-05.png
            "img/noripple-06.png": https://ripple.com/wp-content/uploads/2015/01/noripple-06.png

    -   name: rippled-setup
        display_name: rippled Setup Guide

pages:
# Intro pages is not directly replicated on ripple.com at this time
    -   name: Overview
        html: index.html
        sidebar: false
        template: template-index.html
        targets:
            - local
            - ripple.com

# References are exhaustive lists of commands and options
    -   name: RippleAPI
        category: References
        html: reference-rippleapi.html
        # Currently this is the only page that's fetched remotely.
        md: https://raw.githubusercontent.com/ripple/ripple-lib/0.17.2/docs/index.md
        ripple.com: https://ripple.com/build/rippleapi/
        filters:
            - remove_doctoc
            - add_version
        targets:
            - local
            - ripple.com

    -   name: rippled
        category: References
        html: reference-rippled.html
        md: reference-rippled.md
        ripple.com: https://ripple.com/build/rippled-apis/
        targets:
            - local
            - ripple.com

    -   name: Transaction Format
        category: References
        html: reference-transaction-format.html
        md: reference-transaction-format.md
        ripple.com: https://ripple.com/build/transactions/
        targets:
            - local
            - ripple.com

    -   name: Ledger Format
        category: References
        html: reference-ledger-format.html
        md: reference-ledger-format.md
        ripple.com: https://ripple.com/build/ledger-format/
        targets:
            - local
            - ripple.com

    -   name: Ripple Data API v2
        category: References
        html: reference-data-api.html
        md: reference-data-api.md
        ripple.com: https://ripple.com/build/data-api-v2/
        targets:
            - local
            - ripple.com

# Tutorials are step-by-step guides to a specific goal
    -   name: How to Multi-Sign
        category: Tutorials
        html: tutorial-multisign.html
        md: tutorial-multisign.md
        ripple.com: https://ripple.com/build/how-to-multi-sign/
        targets:
            - local
            - ripple.com

        # This is more like a "best practices" doc than Tutorials...
    -   name: Issuing and Operational Addresses
        category: Tutorials
        html: concept-issuing-and-operational-addresses.html
        md: concept-issuing-and-operational-addresses.md
        ripple.com: https://ripple.com/build/issuing-operational-addresses/
        targets:
            - local
            - ripple.com

    -   name: Reliable Transaction Submission
        category: Tutorials
        html: tutorial-reliable-transaction-submission.html
        md: tutorial-reliable-transaction-submission.md
        ripple.com: https://ripple.com/build/reliable-transaction-submission/
        targets:
            - local
            - ripple.com

    -   name: RippleAPI Beginners Guide
        category: Tutorials
        html: tutorial-rippleapi-beginners-guide.html
        md: tutorial-rippleapi-beginners-guide.md
        ripple.com: https://ripple.com/build/rippleapi-beginners-guide/
        targets:
            - local
            - ripple.com

    -   name: rippled Setup
        category: Tutorials
        html: tutorial-rippled-setup.html
        md: tutorial-rippled-setup.md
        ripple.com: https://ripple.com/build/rippled-setup/
        targets:
            - local
            - ripple.com
            - rippled-setup

        # The Gateway Guide is also a poor fit for the "tutorials" category
    -   name: Gateway Guide
        category: Tutorials
        html: tutorial-gateway-guide.html
        md: tutorial-gateway-guide.md
        ripple.com: https://ripple.com/build/gateway-guide/
        targets:
            - local
            - ripple.com

#RCL Features describe how the RCL works in a mostly conceptual manner
    -   name: Amendments
        category: RCL Features
        html: concept-amendments.html
        md: concept-amendments.md
        ripple.com: https://ripple.com/build/amendments/
        targets:
            - local
            - ripple.com

    -   name: Fee Voting
        category: RCL Features
        html: concept-fee-voting.html
        md: concept-fee-voting.md
        ripple.com: https://ripple.com/build/fee-voting/
        targets:
            - local
            - ripple.com

    -   name: Fees (Disambiguation)
        category: RCL Features
        html: concept-fees.html
        md: concept-fees.md
        ripple.com: https://ripple.com/build/fees-disambiguation/
        targets:
            - local
            - ripple.com

    -   name: Freeze
        category: RCL Features
        html: concept-freeze.html
        md: concept-freeze.md
        ripple.com: https://ripple.com/build/freeze/
        targets:
            - local
            - ripple.com

    -   name: Paths
        category: RCL Features
        html: concept-paths.html
        md: concept-paths.md
        ripple.com: https://ripple.com/build/paths/
        targets:
            - local
            - ripple.com

    -   name: Reserves
        category: RCL Features
        html: concept-reserves.html
        md: concept-reserves.md
        ripple.com: https://ripple.com/build/reserves/
        targets:
            - local
            - ripple.com

    -   name: Stand-Alone Mode
        category: RCL Features
        html: concept-stand-alone-mode.html
        md: concept-stand-alone-mode.md
        ripple.com: https://ripple.com/build/stand-alone-mode/
        targets:
            - local
            - ripple.com

    -   name: Transaction Cost
        category: RCL Features
        html: concept-transaction-cost.html
        md: concept-transaction-cost.md
        ripple.com: https://ripple.com/build/transaction-cost/
        targets:
            - local
            - ripple.com

    -   name: Transfer Fees
        category: RCL Features
        html: concept-transfer-fees.html
        md: concept-transfer-fees.md
        ripple.com: https://ripple.com/build/transfer-fees/
        targets:
            - local
            - ripple.com

    -   name: Understanding the NoRipple flag
        category: RCL Features
        html: concept-noripple.html
        md: concept-noripple.md
        ripple.com: https://ripple.com/build/understanding-the-noripple-flag/
        targets:
            - local
            - ripple.com

    -   name: "GB-2015-06: Corrections to Autobridging"
        category: Gateway Bulletins
        html: gb-2015-06.html
        md: gb-2015-06.md
        ripple.com: https://ripple.com/build/gateway-guide/gb-2015-06-corrections-autobridging/
        targets:
            - local
            - ripple.com

    -   name: "GB-2015-05: Historical Ledger Query Migration"
        category: Gateway Bulletins
        html: gb-2015-05.html
        md: gb-2015-05.md
        ripple.com: https://ripple.com/build/gateway-guide/gb-2015-05-historical-ledger-query-migration/
        targets:
            - local
            - ripple.com

# API tools are interactive software for interfacing with real APIs
    -   name: WebSocket API Tool
        category: API Tools
        html: ripple-api-tool.html
        ripple.com: https://ripple.com/build/websocket-tool/
        sidebar: custom
        targets:
            - local
            - ripple.com
        template: template-ripple-api-tool.html

    -   name: Data API v2 Tool
        category: API Tools
        html: data-api-v2-tool.html
        ripple.com: https://ripple.com/build/data-api-tool/
        methods_js: js/apitool-methods-data_v2.js
        rest_host: https://data.ripple.com
        doc_page: reference-data-api.html
        sidebar: custom
        targets:
            - local
            - ripple.com
        template: template-rest-api-tool.html

    -   name: rippled JSON-RPC Tool
        # This tool requires a local server w/ reverse proxy
        category: API Tools
        html: tool-jsonrpc.html
        methods_js: js/apitool-methods-jsonrpc.js
        rest_host: http://localhost/rippled
        doc_page: reference-rippled.html
        sidebar: custom
        targets:
            - local
            - ripple.com
        template: template-rest-api-tool.html

# Link Checker Config ------------------------------------------------------- #

ignore_anchors_in:
    - data-api-v2-tool.html
    - ripple-api-tool.html
    - tool-jsonrpc.html

#Sometimes, a link is not really problematic, but the link checker detects it
# as such and the easiest solution is to ignore it.
known_broken_links:
    # Strangely, Python doesn't like the cert here. Firefox is OK with it.
    - https://validators.ripple.com

    # rippled 0.33.0 is not released yet:
    - https://github.com/ripple/rippled/releases/tag/0.33.0

# Style Checker Config ------------------------------------------------------ #

word_substitutions_file: word_substitutions.yaml
phrase_substitutions_file: phrase_substitutions.yaml
